
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Button button1;
	private global::Gtk.Label Nombre1;
	private global::Gtk.Label codigo;
	private global::Gtk.Label pregu1;
	private global::Gtk.Entry entry3;
	private global::Gtk.Label opc1;
	private global::Gtk.RadioButton radiobutton1;
	private global::Gtk.RadioButton radiobutton3;
	private global::Gtk.Label pregu2;
	private global::Gtk.SpinButton spinbutton1;
	private global::Gtk.Label pregu3;
	private global::Gtk.Label opc6;
	private global::Gtk.Label opc7;
	private global::Gtk.Label opc8;
	private global::Gtk.CheckButton checkbutton1;
	private global::Gtk.Label opc5;
	private global::Gtk.CheckButton checkbutton2;
	private global::Gtk.CheckButton checkbutton3;
	private global::Gtk.CheckButton checkbutton4;
	private global::Gtk.Label pregu4;
	private global::Gtk.Calendar calendar1;
	private global::Gtk.Entry entry1;
	private global::Gtk.Label grupo;
	private global::Gtk.ComboBoxEntry comboboxentry3;
	private global::Gtk.Label opc2;
	private global::Gtk.RadioButton radiobutton2;
	private global::Gtk.Label opc3;
	private global::Gtk.Label opc4;
	private global::Gtk.RadioButton radiobutton5;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("TERMINAR");
		this.fixed1.Add (this.button1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button1]));
		w1.X = 424;
		w1.Y = 471;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Nombre1 = new global::Gtk.Label ();
		this.Nombre1.Name = "Nombre1";
		this.Nombre1.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre");
		this.fixed1.Add (this.Nombre1);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Nombre1]));
		w2.X = 18;
		w2.Y = 18;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.codigo = new global::Gtk.Label ();
		this.codigo.Name = "codigo";
		this.codigo.LabelProp = global::Mono.Unix.Catalog.GetString ("Codigo");
		this.fixed1.Add (this.codigo);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.codigo]));
		w3.X = 16;
		w3.Y = 43;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.pregu1 = new global::Gtk.Label ();
		this.pregu1.Name = "pregu1";
		this.pregu1.LabelProp = global::Mono.Unix.Catalog.GetString ("1._¿Personaje de la independencia de Mexico?");
		this.fixed1.Add (this.pregu1);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.pregu1]));
		w4.X = 13;
		w4.Y = 70;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry3 = new global::Gtk.Entry ();
		this.entry3.CanFocus = true;
		this.entry3.Name = "entry3";
		this.entry3.IsEditable = true;
		this.entry3.InvisibleChar = '●';
		this.fixed1.Add (this.entry3);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry3]));
		w5.X = 62;
		w5.Y = 42;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.opc1 = new global::Gtk.Label ();
		this.opc1.Name = "opc1";
		this.opc1.LabelProp = global::Mono.Unix.Catalog.GetString ("A)");
		this.fixed1.Add (this.opc1);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.opc1]));
		w6.X = 11;
		w6.Y = 97;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.radiobutton1 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Goku"));
		this.radiobutton1.CanFocus = true;
		this.radiobutton1.Name = "radiobutton1";
		this.radiobutton1.DrawIndicator = true;
		this.radiobutton1.UseUnderline = true;
		this.radiobutton1.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.fixed1.Add (this.radiobutton1);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.radiobutton1]));
		w7.X = 35;
		w7.Y = 96;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.radiobutton3 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Mac flay"));
		this.radiobutton3.CanFocus = true;
		this.radiobutton3.Name = "radiobutton3";
		this.radiobutton3.DrawIndicator = true;
		this.radiobutton3.UseUnderline = true;
		this.radiobutton3.Group = this.radiobutton1.Group;
		this.fixed1.Add (this.radiobutton3);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.radiobutton3]));
		w8.X = 300;
		w8.Y = 97;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.pregu2 = new global::Gtk.Label ();
		this.pregu2.Name = "pregu2";
		this.pregu2.LabelProp = global::Mono.Unix.Catalog.GetString ("2._¿Cuanto es  2 + 2?");
		this.fixed1.Add (this.pregu2);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.pregu2]));
		w9.X = 25;
		w9.Y = 135;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.spinbutton1 = new global::Gtk.SpinButton (0D, 100D, 1D);
		this.spinbutton1.CanFocus = true;
		this.spinbutton1.Name = "spinbutton1";
		this.spinbutton1.Adjustment.PageIncrement = 10D;
		this.spinbutton1.ClimbRate = 1D;
		this.spinbutton1.Numeric = true;
		this.fixed1.Add (this.spinbutton1);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.spinbutton1]));
		w10.X = 43;
		w10.Y = 156;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.pregu3 = new global::Gtk.Label ();
		this.pregu3.Name = "pregu3";
		this.pregu3.LabelProp = global::Mono.Unix.Catalog.GetString ("3._¿Cuales paises son de america?");
		this.fixed1.Add (this.pregu3);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.pregu3]));
		w11.X = 36;
		w11.Y = 190;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.opc6 = new global::Gtk.Label ();
		this.opc6.Name = "opc6";
		this.opc6.LabelProp = global::Mono.Unix.Catalog.GetString ("B)");
		this.fixed1.Add (this.opc6);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.opc6]));
		w12.X = 117;
		w12.Y = 229;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.opc7 = new global::Gtk.Label ();
		this.opc7.Name = "opc7";
		this.opc7.LabelProp = global::Mono.Unix.Catalog.GetString ("C)");
		this.fixed1.Add (this.opc7);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.opc7]));
		w13.X = 211;
		w13.Y = 229;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.opc8 = new global::Gtk.Label ();
		this.opc8.Name = "opc8";
		this.opc8.LabelProp = global::Mono.Unix.Catalog.GetString ("D)");
		this.fixed1.Add (this.opc8);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.opc8]));
		w14.X = 324;
		w14.Y = 228;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.checkbutton1 = new global::Gtk.CheckButton ();
		this.checkbutton1.CanFocus = true;
		this.checkbutton1.Name = "checkbutton1";
		this.checkbutton1.Label = global::Mono.Unix.Catalog.GetString ("Mexico");
		this.checkbutton1.DrawIndicator = true;
		this.checkbutton1.UseUnderline = true;
		this.fixed1.Add (this.checkbutton1);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.checkbutton1]));
		w15.X = 33;
		w15.Y = 224;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.opc5 = new global::Gtk.Label ();
		this.opc5.Name = "opc5";
		this.opc5.LabelProp = global::Mono.Unix.Catalog.GetString ("A)");
		this.fixed1.Add (this.opc5);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.opc5]));
		w16.X = 5;
		w16.Y = 224;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.checkbutton2 = new global::Gtk.CheckButton ();
		this.checkbutton2.CanFocus = true;
		this.checkbutton2.Name = "checkbutton2";
		this.checkbutton2.Label = global::Mono.Unix.Catalog.GetString ("Peru");
		this.checkbutton2.DrawIndicator = true;
		this.checkbutton2.UseUnderline = true;
		this.fixed1.Add (this.checkbutton2);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.checkbutton2]));
		w17.X = 136;
		w17.Y = 227;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.checkbutton3 = new global::Gtk.CheckButton ();
		this.checkbutton3.CanFocus = true;
		this.checkbutton3.Name = "checkbutton3";
		this.checkbutton3.Label = global::Mono.Unix.Catalog.GetString ("Alemania");
		this.checkbutton3.DrawIndicator = true;
		this.checkbutton3.UseUnderline = true;
		this.fixed1.Add (this.checkbutton3);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.checkbutton3]));
		w18.X = 230;
		w18.Y = 226;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.checkbutton4 = new global::Gtk.CheckButton ();
		this.checkbutton4.CanFocus = true;
		this.checkbutton4.Name = "checkbutton4";
		this.checkbutton4.Label = global::Mono.Unix.Catalog.GetString ("Japon");
		this.checkbutton4.DrawIndicator = true;
		this.checkbutton4.UseUnderline = true;
		this.fixed1.Add (this.checkbutton4);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.checkbutton4]));
		w19.X = 344;
		w19.Y = 226;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.pregu4 = new global::Gtk.Label ();
		this.pregu4.Name = "pregu4";
		this.pregu4.LabelProp = global::Mono.Unix.Catalog.GetString ("4._ Indique la fecha de la independencia de Mexico.");
		this.fixed1.Add (this.pregu4);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.pregu4]));
		w20.X = 34;
		w20.Y = 255;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.calendar1 = new global::Gtk.Calendar ();
		this.calendar1.CanFocus = true;
		this.calendar1.Name = "calendar1";
		this.calendar1.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
		this.fixed1.Add (this.calendar1);
		global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.calendar1]));
		w21.X = 25;
		w21.Y = 303;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry1 = new global::Gtk.Entry ();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.WidthChars = 40;
		this.entry1.InvisibleChar = '●';
		this.fixed1.Add (this.entry1);
		global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry1]));
		w22.X = 63;
		w22.Y = 16;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.grupo = new global::Gtk.Label ();
		this.grupo.Name = "grupo";
		this.grupo.LabelProp = global::Mono.Unix.Catalog.GetString ("Grupo");
		this.fixed1.Add (this.grupo);
		global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.grupo]));
		w23.X = 345;
		w23.Y = 21;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.comboboxentry3 = global::Gtk.ComboBoxEntry.NewText ();
		this.comboboxentry3.WidthRequest = 82;
		this.comboboxentry3.Name = "comboboxentry3";
		this.fixed1.Add (this.comboboxentry3);
		global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.comboboxentry3]));
		w24.X = 398;
		w24.Y = 18;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.opc2 = new global::Gtk.Label ();
		this.opc2.Name = "opc2";
		this.opc2.LabelProp = global::Mono.Unix.Catalog.GetString ("B)");
		this.fixed1.Add (this.opc2);
		global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.opc2]));
		w25.X = 98;
		w25.Y = 98;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.radiobutton2 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Miguel Hidalgo y Costilla"));
		this.radiobutton2.CanFocus = true;
		this.radiobutton2.Name = "radiobutton2";
		this.radiobutton2.DrawIndicator = true;
		this.radiobutton2.UseUnderline = true;
		this.radiobutton2.Group = this.radiobutton1.Group;
		this.fixed1.Add (this.radiobutton2);
		global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.radiobutton2]));
		w26.X = 111;
		w26.Y = 96;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.opc3 = new global::Gtk.Label ();
		this.opc3.Name = "opc3";
		this.opc3.LabelProp = global::Mono.Unix.Catalog.GetString ("C)");
		this.fixed1.Add (this.opc3);
		global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.opc3]));
		w27.X = 273;
		w27.Y = 98;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.opc4 = new global::Gtk.Label ();
		this.opc4.Name = "opc4";
		this.opc4.LabelProp = global::Mono.Unix.Catalog.GetString ("D)");
		this.fixed1.Add (this.opc4);
		global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.opc4]));
		w28.X = 386;
		w28.Y = 100;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.radiobutton5 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Crissty (Panque)"));
		this.radiobutton5.CanFocus = true;
		this.radiobutton5.Name = "radiobutton5";
		this.radiobutton5.DrawIndicator = true;
		this.radiobutton5.UseUnderline = true;
		this.radiobutton5.Group = this.radiobutton1.Group;
		this.fixed1.Add (this.radiobutton5);
		global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.radiobutton5]));
		w29.X = 411;
		w29.Y = 98;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 554;
		this.DefaultHeight = 542;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.button1.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
	}
}
